### ISSUE TITLE
Add a method to track awarded in tracker accrued/awarded

### ISSUE THREAD

**Issue by Merovex** [Merovex/leaf-blower#9]
- [X] Accural: Indicate need to update Troop Track (TT), branch award
- [x] Accural: Indicate need to update TT, star award
- [x] Record: Need to allow Advancement Chair to report that TT was updated, branch award
- [x] Record: Need to allow Advancement Chair to report that TT was updated, star award
- [x] Fast link from Boys#index when need to record, branch & star award.
- [x] Restrict record to advancement chair to avoid false positives.

**Comment by Merovex** [comment]
Have implemented the ability to annotate accural, and to have somebody assign.
